DirectoryIteratorException (Java SE 21 & JDK 21)
JavaScript is disabled on your browser.
Skip navigation links
Java SE 21 & JDK 21
Overview
Module
Package
Class
Use
Tree
Preview
New
Deprecated
Index
Help
Summary:
Nested
Field
Constr
Method
Detail:
Field
Constr
Method
Summary:
Nested |
Field |
Constr
|
Method
Detail:
Field |
Constr
|
Method
SEARCH
Module
java.base
Package
java.nio.file
Class DirectoryIteratorException
java.lang.Object
java.lang.Throwable
java.lang.Exception
java.lang.RuntimeException
java.util.ConcurrentModificationException
java.nio.file.DirectoryIteratorException
All Implemented Interfaces:
Serializable
public final class
DirectoryIteratorException
extends
ConcurrentModificationException
Runtime exception thrown if an I/O error is encountered when iterating over
 the entries in a directory. The I/O error is retrieved as an
IOException
using the
getCause()
method.
Since:
1.7
See Also:
DirectoryStream
Serialized Form
Constructor Summary
Constructors
Constructor
Description
DirectoryIteratorException
(
IOException
cause)
Constructs an instance of this class.
Method Summary
All Methods
Instance Methods
Concrete Methods
Modifier and Type
Method
Description
IOException
getCause
()
Returns the cause of this exception.
Methods declared in class java.lang.
Throwable
addSuppressed
,
fillInStackTrace
,
getLocalizedMessage
,
getMessage
,
getStackTrace
,
getSuppressed
,
initCause
,
printStackTrace
,
printStackTrace
,
printStackTrace
,
setStackTrace
,
toString
Methods declared in class java.lang.
Object
clone
,
equals
,
finalize
,
getClass
,
hashCode
,
notify
,
notifyAll
,
wait
,
wait
,
wait
Constructor Details
DirectoryIteratorException
public
DirectoryIteratorException
(
IOException
cause)
Constructs an instance of this class.
Parameters:
cause
- the
IOException
that caused the directory iteration
          to fail
Throws:
NullPointerException
- if the cause is
null
Method Details
getCause
public
IOException
getCause
()
Returns the cause of this exception.
Overrides:
getCause
in class
Throwable
Returns:
the cause
Report a bug or suggest an enhancement
For further API reference and developer documentation see the
Java SE Documentation
, which contains more detailed, developer-targeted descriptions with conceptual overviews, definitions of terms, workarounds, and working code examples.
Other versions.
Java is a trademark or registered trademark of Oracle and/or its affiliates in the US and other countries.
Copyright
© 1993, 2024, Oracle and/or its affiliates, 500 Oracle Parkway, Redwood Shores, CA 94065 USA.
All rights reserved. Use is subject to
license terms
and the
documentation redistribution policy
.